apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kn-controller
  namespace: default
  labels:
    app: kn-controller
    control-plane: kn-controller
spec:
  selector:
    matchLabels:
      control-plane: kn-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: kn-controller
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: hub.xesv5.com/wangxiao-jichujiagou-common/kn-controller:latest
        name: kn-controller
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
